all:

	g++ ./src/main.cpp ./src/Read.hpp ./src/Read.cpp ./src/Fila.hpp ./src/Fila.cpp ./src/heapSort.hpp ./src/heapSort.cpp -o ./build/objects/executavel

clean:

	rm -rf ./build/objects/executavel

run:

	./build/objects/executavel